apiVersion: v1
kind: Pod
metadata:
  name: client-pod
  labels:
    component: web
spec:
  containers:
    - name: client
      image: shaggybb/multi-docker-client
      ports:
        - containerPort: 3000 #It's related to the ngnix port inside multi-client
